language: cpp
matrix:
  include:
  - os: linux
    dist: trusty
    env: TOXENV=WIN
    sudo: false
  - os: linux
    dist: trusty
    sudo: false
  - os: osx
    osx_image: xcode9.4
addons:
  apt:
    packages:
    - g++-mingw-w64
    - cmake3
before_script:
- export PATH="$HOME/bin:$PATH"
- make -f texinfo-travis.mk install_texinfo
script:
- export REV=dirty-$(git describe --always)
- git clone https://github.com/planas/buildscripts.git
- chmod +x *.sh
- "./build.sh"
branches:
  except:
  - "/^*-v[0-9]/"
deploy:
  provider: releases
  api_key:
    secure: ZlqB/O5Diy41PBbfHs9KzjVOfahGrs2h881AvsAx/OyZNcb/TWYWP6TFJztse8IDP6dBKHztFxjrhG1vnKjcLKl276fVZ/W5FlVpq4CI1k218gQo2M1ZJj28uRW6xk+GRGSOgfH4ev4HGFxuOUr/Fx88WXnOxCmq29bRpR/p8L+UMvxbm/CHvnAbRtmO9Txy3mo7AKCOAOQDFALWSGD4LV8Ln2yClNmJBTU7yyB0jFe31kJQOEZYU4GNOw1aUQzL3VlJwaD5UvJpBn1+TaL4LDHTgYspMrKKaS1xbxU/0/RA8jo/XHjoJgOnfgg+TfJgTJDCkdGZI20Lya/fyNSITSpRvRRR9sSmsM39gOyAQooqkEhWPwFp+JNjZfeTttpWohpcToYoTWK2P3HT1cVcHj8YBbx5CDu6XbquVduArsHeJ6L5a9aVG1P1DEaOgaU2M4/YFlSQeTvA1ABG1tgM0Uezqc6chDxkjt5xHfUyU4+MEGV8jTWqw9n2m2dul1DczJEAZ6or7jLsIS1AQevbx2ckFf36Hq0PNUBuSwp97VdQjNhjIzNQBZSU/GUTaa92Bm0Ed72Ry2YAxs9uQDnZ5VTYwqNdQ+4sUq3a6TEabGE6JnE9zr1iVSu0sM4ufvwmiNOaaFO8SrASGbkhfJ9RqF3sVf1nCnmIuZvJllZSa8g=
  file: buildscripts/build/*.tar.bz2
  file_glob: true
  skip_cleanup: true
  on:
    repo: planas/autobuilds
